[package]
name = "mhtest"
version = "0.1.0"
authors = ["kolen <incredible.angst@gmail.com>"]
edition = "2018"

[dependencies]
serial = "0.4.0"
embedded-hal = "0.2.4"
serial-embedded-hal = "0.1.2"
mh-z19 = "0.3.0"
nb = "0.1.2"